# Generated by Django 4.2.4 on 2023-08-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepient_name', models.CharField(max_length=255, verbose_name='Recipient name')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('administrative_area', models.CharField(blank=True, default='', max_length=20, verbose_name='Administrative area')),
                ('locality', models.CharField(blank=True, default='', max_length=255, verbose_name='City/town')),
                ('address_line', models.CharField(max_length=255, verbose_name='Street number and name')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('additional_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
