# Generated by Django 4.2.4 on 2023-08-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_name',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug name'),
        ),
    ]
