# Generated by Django 4.2.4 on 2023-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=None, upload_to='brands/', verbose_name='Brand image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(max_length=1020, verbose_name='Description'),
        ),
    ]
